#!/bin/sh
rsync -av -e 'ssh -p 5022' ./ aitkmgzy@world-373.fr.planethoster.net:~/public_html --include=public/build --include=public/.htaccess --include=vendor --exclude-from=.gitignore --exclude=".env" --exclude=".*"
